# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
light: !include lights.yaml

nest:
  client_id: 6927190241-5ujsk7ckfl4nubbvtkk1q53ncdmro24e.apps.googleusercontent.com
  client_secret: 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
  project_id: 0dc8af53-b4d4-4ff3-8a36-794825eacd4e

sonoff:
  username: lantz.leiweke@gmail.com
  password: Chirom0nk!13!
